### ISSUE TITLE
stopped at Downloading any NPM components found in the template.

### ISSUE THREAD

**Issue by zhangchunsheng** [serverless-components/tencent-website#11]
DEBUG ─ Downloading any NPM components found in the template.

22s › Template > Deploying

**Comment by tinafangkunding** [comment]
Hi 您好，感谢反馈，这里正在做下列优化：

当前在npm下载相关component的时候由于网络等原因会比较慢。三月底即将支持从云端的注册中心下载关联的组件，这样就可以有效避免当前的问题。
