### ISSUE TITLE
How to  enable default CDN acceleration domain for cos?

### ISSUE THREAD

**Issue by zhuangdx** [serverless-components/tencent-website#12]
Excuse me,
I can configure custom domain in compose. 
But I don't have a domain, and hope to use default CDN domain.
Unfortunately, I can not find how to do.
Please teach me how to do, thank.
If not support , could it be a request?

**Comment by tinafangkunding** [comment]
hi 您好，当前的文档已经更新，github中的配置也已经更新。可以参考如下方案进行CDN的加速配置。
https://cloud.tencent.com/document/product/1154/41321 
```
文档中心  Serverless Framework  最佳实践  自定义域名及 HTTPS 访问配置
自定义域名及 HTTPS 访问配置
最近更新时间：2020-02-18 11:58:38

 编辑  查看pdf
操作场景
前提条件
方案一：通过 CDN 加速配置支持自定义域名的 HTTPS 访问
增加配置
部署服务
添加 CNAME
方案二：对 API 网关域名进行自定义域名配置
增加配置
部署服务
添加 CNAME 记录
操作场景
通过 Serverless Component 快速构建一个 Serverless Web 网站服务后，如果您希望配置自定义域名及支持 HTTPS 的访问，则可以按照本文提供的两种方案快速配置。

前提条件
已经部署了网站服务，获取了 COS/API 网关的网站托管地址。具体部署方法参考 部署 Vue.js+Express.js 全栈应用 或 快速部署 Hexo 博客。
已拥有自定义域名（例如 www.example.com），并确保输入的域名已 备案。
如果需要 HTTPS 访问，可以申请证书并且 获得证书 ID （例如：certificateId : axE1bo3），个人站点可以直接申请 域名型（DV）免费SSL证书。
方案一：通过 CDN 加速配置支持自定义域名的 HTTPS 访问
配置前，需要确保账号实名并已经 开通 CDN 服务。

增加配置
在 serverless.yml 中，增加 CDN 自定义域名配置：

myWebsite:
  myWebsite:
  component: '@serverless/tencent-website'
  inputs:
    code:
      src: ./public # Upload static files generated by HEXO
      index: index.html
      error: index.html
    region: ap-guangzhou
    bucketName: my-hexo-bucket
    protocol: https
    # 新增的 CDN 自定义域名配置
    hosts:
      - host: www.example.com # 希望配置的自定义域名
        https:
          certId: axE1bo3 # SSL 证书 ID
          http2: off
          httpsType: 4
          forceSwitch: -2
```

**Comment by tinafangkunding** [comment]
默认的 CDN 域名加速能力需要进一步开发 @yugasun 辛苦帮忙看下哈

**Comment by yugasun** [comment]
目前不支持默认CDN加速不支持。

**Comment by die214144031** [comment]
静态网站接入了自有域名，但是怎么配置成https呢？
我按照上面的新增的 CDN 自定义域名配置好后，重新部署成功，没有报错，但是不生效。
打开网页还是显示不安全
证书是有效的，只配置了证书id

**Comment by yugasun** [comment]
可以贴一下yml配置，然后核查下CDN加速域名的 CNAME 配了吗？

**Comment by die214144031** [comment]
![image](https://user-images.githubusercontent.com/11813890/77638811-b4f3b400-6f92-11ea-92b5-60f05c832c26.png)
![image](https://user-images.githubusercontent.com/11813890/77638771-a86f5b80-6f92-11ea-946b-c9aa51517863.png)
![image](https://user-images.githubusercontent.com/11813890/77638885-d5237300-6f92-11ea-8667-f69860a2150e.png)

@yugasun 有空帮忙看下，Thanks

**Comment by yugasun** [comment]
@die214144031 yml 配置缩进有问题，如图红色圈起来的地方：

![image](https://user-images.githubusercontent.com/8536173/77648075-84b41180-6fa2-11ea-8acf-786b227c9ad9.png)

**Comment by die214144031** [comment]
![image](https://user-images.githubusercontent.com/11813890/77717423-66d6c300-701b-11ea-9078-abcb2c06789a.png)
![image](https://user-images.githubusercontent.com/11813890/77717432-6f2efe00-701b-11ea-80b9-54c02d6a71b9.png)
@yugasun 貌似还是不行

**Comment by tinafangkunding** [comment]
我刚才校验了一下自己的配置，和你的是一样的，我这边看是可以HTTPS访问的。

```yml
  myWebsite: 
    url:  https://my-hexo-bucket-120200202.cos-website.ap-guangzhou.myqcloud.com
    env: 
    host: 
      - https://www.example.com (CNAME: www.example.com.cdn.dnsv1.com）

  109s › myWebsite › done
```

**Comment by zhuangdx** [comment]
好吧，后续有更新支持默认cdn的话，希望可以告知下。
另外其他评论是否可以另开issue，麻烦管理关闭issue吗，
