### ISSUE TITLE
如何覆盖bucket

### ISSUE THREAD

**Issue by DaZiYuan** [serverless-components/tencent-website#2]
同样的代码，我在不同的电脑执行
```
sls --debug
```
会报错
```
error:
  {     
  error: {
    Code: 'BucketAlreadyOwnedByYou',
    Message: 'Your previous request to create the named bucket succeeded and you already own it.',       
    Resource: 'xxxx-1251120934.cos.ap-guangzhou.myqcloud.com',
    RequestId: 'NWRlZGUyMjdfMWZiZTk0MGFfYWI3OF8zZTdmNmI=',
    TraceId: 'OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODczNTBmNjMwZmQ0MTZkMjg0NjlkNTYyNmY4ZTRkZTk0NzJmZTI0ZmJhYTZmZjYyNmU5ZGNlZDI5YjkyODkwYjNhN2MyMTYxN2NhOGE5YjMyYjE2MzI4NzljYTllNDc4N2Q='
  },
  statusCode: 409,
  headers: {
    'content-type': 'application/xml',
    'content-length': '540',
    connection: 'keep-alive',
    date: 'Mon, 09 Dec 2019 05:56:55 GMT',
    server: 'tencent-cos',
    'x-cos-request-id': 'NWRlZGUyMjdfMWZiZTk0MGFfYWI3OF8zZTdmNmI=',
    'x-cos-trace-id': 'OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODczNTBmNjMwZmQ0MTZkMjg0NjlkNTYyNmY4ZTRkZTk0NzJmZTI0ZmJhYTZmZjYyNmU5ZGNlZDI5YjkyODkwYjNhN2MyMTYxN2NhOGE5YjMyYjE2MzI4NzljYTllNDc4N2Q='
  }
}
```
配置信息
```
my-test-site:
  component: "@serverless/tencent-website"
  inputs:
    region: ap-guangzhou
    bucketName: xxxx
...

**Comment by pmuens** [comment]
Hey @DaZiYuan thanks for opening :+1:

Could you provide some more information on your service? Are you re-using an existing bucket or are you letting `serverless` create and manage the bucket for you?

I just created a new `tencent-websiste` project and tested whether multiple re-deploys trigger this problem. (Un)fortunately I was not able to reproduce this problem.

Would be nice if we could find a way to reliably reproduce the problem to work on a fix.

Let us know if you have any question / need any help here.

**Comment by DaZiYuan** [comment]
Hi @pmuens ,
You can try this demo, replace .env with your config
https://github.com/DaZiYuan/test-serverless

**Comment by pmuens** [comment]
@DaZiYuan thanks for getting back 👍

I just deployed the linked project but I wasn't able to run into the same issue you ran into. Still not exactly sure why you're seeing the error. One potential cause could be that you were using a bucket name which was already taken (e.g. when following a tutorial)... Still not sure, if that is the main problem 🤔

**Comment by DaZiYuan** [comment]
I defined the bucket name in serverless.yml and deploy it from pc A.
then use the same code deploy it from pc B. will repro this issue

**Comment by pmuens** [comment]
Ahh, that makes sense. Thanks @DaZiYuan 👍

**Comment by DaZiYuan** [comment]
Is there any way can overwrite bucket? because  I want to continue my work even changed computer

**Comment by yugasun** [comment]
@DaZiYuan I have solve this bug for this pr https://github.com/serverless-components/tencent-cos/pull/3

**Comment by DaZiYuan** [comment]
@yugasun  What time I can test this? I just install new serverless, seems the issue still exists.

**Comment by yugasun** [comment]
@DaZiYuan After @pmuens merge this pr.

**Comment by yugasun** [comment]
@DaZiYuan This bug has been fixed, you can try it again.

**Comment by DaZiYuan** [comment]
It works correctly now, Thanks for helping @yugasun ,@pmuens
