### ISSUE TITLE
静态网站腾讯云cos部署如何做url重写？现在直接访问不存在的路径会404

### ISSUE THREAD

**Issue by zsp042** [serverless-components/tencent-website#4]
静态网站腾讯云cos部署如何做url重写？现在直接访问不存在的路径会404

**Comment by pmuens** [comment]
Hey @TqLj thanks for opening :+1:

Could you share more details about the service you've been using? How does your `serverless.yml` look like? What were the steps you took so that you ran into this problem?

Thanks in advance!

**Comment by yugasun** [comment]
@TqLj 目前可以在COS 控制台进行手动配置，如下图：
![image](https://user-images.githubusercontent.com/8536173/72245121-c5022580-362a-11ea-8381-e06fe1bb29bb.png)
