### ISSUE TITLE
refreshCdn 配置项报错  The value type of parameter `Filters.0.Value.0` is not valid.

### ISSUE THREAD

**Issue by sonofmagic** [serverless-components/tencent-website#40]
建议抛出更加友好一些，不然不知道哪里的问题呢

后面又有 当前操作已超出频次限制，请等待后重试 (reqId: 0ff83641-bf59-4b87-b90a-9a542b0cd80d)

**Comment by yugasun** [comment]
@sonofmagic 可否提供下yaml 配置，方便问题定位
